---

- name: Ensure redis is installed
  community.general.pkgng:
    state: present
    name: redis
    autoremove: true
    cached: false

- name: Enable redis
  community.general.sysrc:
    name: redis_enable
    state: present
    value: "YES"
