locale: "en_US.UTF-8"
timezone: "America/Los_Angeles"

poudriere: false
postgresql: false
redis: false

dotfiles_repo: "https://github.com/charlesrocket/dotfiles.git"
dotfiles_repo_version: master
dotfiles_repo_accept_hostkey: true
dotfiles_repo_force: true
dotfiles_repo_local_destination: "~/git/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .config/mc/ini
  - .gitconfig

pkgng_packages:
  - bash
  - bastille
  - bzip2
  - chkrootkit
  - clamav
  - crystal
  - curl
  - devcpu-data
  - diffutils
  - direnv
  - exfat-utils
  - fdupes
  - figlet
  - gawk
  - gcc
  - git
  - gnupg
  - gzip
  - htop
  - httping
  - iftop
  - less
  - lolcat
  - lynis
  - mc
  - netcat
  - nmap
  - openssl
  - p7zip
  - pv
  - pwgen
  - rkhunter
  - shards
  - sshpass
  - sudo
  - tmux
  - tig
  - unzip
  - wget
  - whois
  - wireguard
  - zsh
