locale: "en_US.UTF-8"
timezone: "America/Los_Angeles"

accounting: false
bastille: false
poudriere: false
postgresql: false
redis: false

upgrade_packages: false
set_security_level: false
security_level: 3

dotfiles_repo: "https://github.com/charlesrocket/dotfiles.git"
dotfiles_repo_version: fbsd-server
dotfiles_repo_accept_hostkey: true
dotfiles_repo_force: true
dotfiles_repo_local_destination: "~/git/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .config/mc/ini
  - .gitconfig
  - .shrc
  - .zshrc

pkgng_packages:
  - bastille
  - bzip2
  - chkrootkit
  - clamav
  - crystal
  - curl
  - devcpu-data
  - diffutils
  - direnv
  - exfat-utils
  - fdupes
  - figlet
  - gawk
  - gcc
  - git
  - gnupg
  - gzip
  - htop
  - httping
  - iftop
  - less
  - lolcat
  - lynis
  - lynx
  - mc
  - netcat
  - nmap
# - openssl
  - p7zip
  - pam_yubico
  - pv
  - pwgen
  - rkhunter
  - rust
  - shards
  - sshpass
  - sudo
  - tig
  - tmux
  - transmission-cli
  - transmission-daemon
  - unzip
  - wget
  - whois
  - wireguard
