---
# Dotfiles
dotfiles_repo: "https://github.com/charlesrocket/dotfiles.git"
dotfiles_repo_version: fbsd-server
dotfiles_repo_accept_hostkey: true
dotfiles_repo_force: true
dotfiles_repo_local_destination: "~/src/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .config/mc/ini
  - .gitconfig
  - .shrc
  - .zshrc

# Configuration
auto_fetch: false
accounting: false
bastille: true
poudriere: false

bastille_zfs_enable: "YES"
bastille_zfs_zpool: "zroot"
hostname:
sshd_enable: "YES"
timezone: "America/Los_Angeles"
make_config:
  - "MAKE_JOBS_NUMBER?=3"

set_security_level: false
security_level: 3

# Keep packages up to date
upgrade_packages: true

# Packages
pkgng_packages:
  - chkrootkit
  - clamav
  - curl
  - destroy
  - devcpu-data
  - diffutils
  - direnv
  - exfat-utils
  - figlet
  - gawk
  - git
  - gnupg
  - gzip
  - htop
  - httping
  - iftop
  - less
  - lolcat
  - lynis
  - lynx
  - mc
  - netcat
  - pam_yubico
  - pciutils
  - pv
  - pwgen
  - rkhunter
  - screen
  - tmux
  - unzip
  - wget
  - whois
  - wireguard
  - zsh
