locale: "en_US.UTF-8"
timezone: "America/Los_Angeles"

postgresql: false
redis: false

pkgng_packages:
  - bash
  - bastille
  - bzip2
  - chkrootkit
  - clamav
  - crystal
  - curl
  - diffutils
  - direnv
  - exfat-utils
  - fdupes
  - figlet
  - gawk
  - gcc
  - git
  - gnupg
  - gzip
  - htop
  - httping
  - iftop
  - less
  - lolcat
  - lynis
  - mc
  - netcat
  - nmap
  - openssl
  - p7zip
  - pv
  - pwgen
  - rkhunter
  - shards
  - sshpass
  - sudo
  - tmux
  - tig
  - unzip
  - wget
  - whois
  - wireguard
  - zsh
