locale: "en_US.UTF-8"
timezone: "America/Los_Angeles"

postgresql: false
redis: false

ssh:
  start: true
  service_enabled: true
  password_auth: false
  root_login: false

pkgng_packages:
  - bash
  - bastille
  - bzip2
  - chkrootkit
  - clamav
  - curl
  - diffutils
  - direnv
  - exfat-utils
  - fdupes
  - figlet
  - gawk
  - gcc
  - git
  - gnupg
  - gzip
  - htop
  - httping
  - iftop
  - less
  - lolcat
  - lynis
  - mc
  - netcat
  - nmap
  - openssl
  - p7zip
  - pv
  - pwgen
  - rkhunter
  - sshpass
  - sudo
  - tmux
  - tig
  - unzip
  - vim
  - wget
  - whois
  - wireguard
  - zsh
