---
# Settings
locale: "en_US.UTF-8"
timezone: "America/Los_Angeles"

# Dotfiles
dotfiles_repo: "https://github.com/charlesrocket/dotfiles.git"
dotfiles_repo_version: fbsd-server
dotfiles_repo_accept_hostkey: true
dotfiles_repo_force: true
dotfiles_repo_local_destination: "~/git/dotfiles"
dotfiles_home: "~"
dotfiles_files:
  - .config/mc/ini
  - .gitconfig
  - .shrc
  - .zshrc

# Configuration
accounting: false
bastille: false
poudriere: false
postgresql: false

hostname:

make_config:
  - "MAKE_JOBS_NUMBER?=3"

set_security_level: false
security_level: 3

# Keep packages up to date
upgrade_packages: false

# Packages
pkgng_packages:
  - bastille
  - chkrootkit
  - clamav
  - curl
  - destroy
  - devcpu-data
  - diffutils
  - direnv
  - exfat-utils
  - fdupes
  - figlet
  - gawk
  - gcc
  - git
  - gnupg
  - gzip
  - htop
  - httping
  - iftop
  - less
  - lolcat
  - lynis
  - lynx
  - mc
  - netcat
  - nmap
# - openssl
  - p7zip
  - pam_yubico
  - pv
  - pwgen
  - rbenv
  - rkhunter
  - screen
  - sshpass
  - sudo
  - tig
  - tmux
  - transmission-cli
  - transmission-daemon
  - unzip
  - wget
  - whois
  - wireguard
  - zsh
