---
- name: Freebsd playbook
  hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Load config.yml
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: pkg
    - role: postgresql
      when: postgresql
      become: True
    - role: redis
      when: redis
      become: True
    - role: common
    - role: ssh
      become: True
