---
- name: FreeBSD Server
  hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Load config.yml
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - {role: pkg}
    - {role: bastille, when: bastille, become: true}
    - {role: poudriere, when: poudriere, become: true}
    - {role: postgresql, when: postgresql, become: true}
    - {role: redis, when: redis, become: true}
    - {role: common}
    - {role: sys, become: true}
    - {role: acct, when: accounting, become: true}
