---
- name: FreeBSD Server
  hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Load config.yml
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: pkg
      become: true

    - role: sys
      become: true

    - role: pf
      when: bastille or pf
      become: true

    - role: common

    - role: charlesrocket.essential.git
      when: git or poudriere

    - role: charlesrocket.essential.dotfiles
      when: dotfiles

    - role: acct
      when: accounting
      become: true

    - role: bastille
      when: bastille
      become: true

    - role: poudriere
      when: poudriere
      become: true

  post_tasks:
    - name: Upgrade installed packages
      community.general.pkgng:
        name: "*"
        state: latest
        autoremove: true
        cached: false
      become: true
      when: upgrade_packages
