---

- name: Copy pf configuration
  ansible.builtin.template:
    src: pf.conf.j2
    dest: /etc/pf.conf
    owner: root
    group: wheel
    mode: '0644'
  notify:
    - Add loopback interface
    - Set loopback interface name
    - Enable loopback interface

- name: Ensure pf is enabled
  community.general.sysrc:
    name: pf_enable
    value: "YES"
    state: present
