---

- name: Ensure packages are installed
  community.general.pkgng:
    state: present
    name:
      - poudriere
      - ccache
    autoremove: true
    cached: false

- name: Copy poudriere config
  ansible.builtin.template:
    src: poudriere.conf.j2
    dest: /usr/local/etc/poudriere.conf
    owner: root
    mode: 0644
