---

- name: Ensure poudriere is installed
  community.general.pkgng:
    state: present
    name: poudriere
    autoremove: true
    cached: false

- name: Ensure nginx is installed
  community.general.pkgng:
    state: present
    name: nginx
    autoremove: true
    cached: false

- name: Ensure ccache is installed
  community.general.pkgng:
    state: present
    name: ccache
    autoremove: true
    cached: false

- name: Copy poudriere config
  ansible.builtin.template:
    src: poudriere.conf.j2
    dest: /usr/local/etc/poudriere.conf
    owner: root
    mode: 0644

- name: Copy nginx config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf
    owner: root
    mode: 0644
