---

- name: Enable process accounting
  community.general.sysrc:
    name: accounting_enable
    state: present
    value: "YES"

- name: Start process accounting
  ansible.builtin.service:
    name: accounting
    state: started
