---

- name: Set hostname
  community.general.sysrc:
    name: hostname
    value: "{{ hostname }}"
    state: present
  when: hostname

- name: Tune TTYs
  ansible.builtin.replace:
    path: /etc/ttys
    regexp: '(?:^|\W)secure(?:$|\W)'
    replace: ' insecure'

- name: Disallow keymap changes for non-privileged users
  ansible.posix.sysctl:
    name: hw.kbd.keymap_restrict_change
    state: present
    value: '4'

- name: Hide UIDs
  ansible.posix.sysctl:
    name: security.bsd.see_other_uids
    state: present
    value: '0'

- name: Hide GIDs
  ansible.posix.sysctl:
    name: security.bsd.see_other_gids
    state: present
    value: '0'

- name: Hide processes running in jails
  ansible.posix.sysctl:
    name: security.bsd.see_jail_proc
    state: present
    value: '0'

- name: Random IP packet IDs
  ansible.posix.sysctl:
    name: net.inet.ip.random_id
    state: present
    value: '1'

- name: Disable reading kernel message buffer
  ansible.posix.sysctl:
    name: security.bsd.unprivileged_read_msgbuf
    state: present
    value: '0'

- name: Disable process debugging facilities
  ansible.posix.sysctl:
    name: security.bsd.unprivileged_proc_debug
    state: present
    value: '0'

- name: Blackhole TCP
  ansible.posix.sysctl:
    name: net.inet.tcp.blackhole
    state: present
    value: '2'

- name: Blackhole UDP
  ansible.posix.sysctl:
    name: net.inet.udp.blackhole
    state: present
    value: '1'

- name: Tune loopback interface
  ansible.posix.sysctl:
    name: net.inet.tcp.nolocaltimewait
    state: present
    value: '1'

- name: Enable H-TCP
  community.general.sysrc:
    name: cc_htcp_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Activate H-TCP
  ansible.posix.sysctl:
    name: inet.tcp.cc.algorithm
    state: present
    value: "htcp"

- name: Enable microcode updates
  community.general.sysrc:
    name: microcode_update_enable
    value: "YES"
    state: present

- name: Enable coretemp
  community.general.sysrc:
    name: coretemp_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable AES
  community.general.sysrc:
    name: aesni_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable AHCI
  community.general.sysrc:
    name: ahci_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable aio
  community.general.sysrc:
    name: aio_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Clear /tmp
  community.general.sysrc:
    name: clear_tmp_enable
    value: "YES"
    state: present

- name: Change loader logo
  community.general.sysrc:
    name: loader_logo
    state: present
    value: "beastie"
    path: /boot/loader.conf

- name: Enable sshd
  community.general.sysrc:
    name: sshd_enable
    value: "YES"
    state: present

- name: Set syslogd flags
  community.general.sysrc:
    name: syslogd_flags
    value: "-ss"
    state: present

- name: Enable Kernel security levels
  community.general.sysrc:
    name: kern_securelevel_enable
    value: "YES"
    state: present
  when: set_security_level

- name: Set kernel security level
  community.general.sysrc:
    name: kern_securelevel
    value: "{{ security_level }}"
    state: present
  when: set_security_level
