---

- name: Set hostname
  community.general.sysrc:
    name: hostname
    value: "{{ hostname }}"
    state: present
  when: hostname

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Tune TTYs
  ansible.builtin.replace:
    path: /etc/ttys
    regexp: '(?:^|\W)secure(?:$|\W)'
    replace: ' insecure'

- name: Disallow keymap changes for non-privileged users
  ansible.posix.sysctl:
    name: hw.kbd.keymap_restrict_change
    state: present
    value: '4'

- name: Verify packets
  ansible.posix.sysctl:
    name: net.inet.ip.check_interface
    state: present
    value: '1'

- name: Hide UIDs
  ansible.posix.sysctl:
    name: security.bsd.see_other_uids
    state: present
    value: '0'

- name: Hide GIDs
  ansible.posix.sysctl:
    name: security.bsd.see_other_gids
    state: present
    value: '0'

- name: Hide processes running in jails
  ansible.posix.sysctl:
    name: security.bsd.see_jail_proc
    state: present
    value: '0'

- name: Disable reading kernel message buffer
  ansible.posix.sysctl:
    name: security.bsd.unprivileged_read_msgbuf
    state: present
    value: '0'

- name: Disable process debugging facilities
  ansible.posix.sysctl:
    name: security.bsd.unprivileged_proc_debug
    state: present
    value: '0'

- name: Random IP packet IDs
  ansible.posix.sysctl:
    name: net.inet.ip.random_id
    state: present
    value: '1'

- name: Do not process IP options
  ansible.posix.sysctl:
    name: net.inet.ip.process_options
    state: present
    value: '0'

- name: Blackhole TCP
  ansible.posix.sysctl:
    name: net.inet.tcp.blackhole
    state: present
    value: '2'

- name: Blackhole UDP
  ansible.posix.sysctl:
    name: net.inet.udp.blackhole
    state: present
    value: '1'

- name: Tune loopback interface
  ansible.posix.sysctl:
    name: net.inet.tcp.nolocaltimewait
    state: present
    value: '1'

- name: Disable PMTUD
  ansible.posix.sysctl:
    name: net.inet.tcp.path_mtu_discovery
    state: present
    value: '0'

- name: Disable TCP keepalive
  ansible.posix.sysctl:
    name: net.inet.tcp.always_keepalive
    state: present
    value: '0'

- name: Drop SYN/FIN packets
  ansible.posix.sysctl:
    name: net.inet.tcp.drop_synfin
    state: present
    value: '1'

- name: Disable ICMP RST
  ansible.posix.sysctl:
    name: net.inet.tcp.icmp_may_rst
    state: present
    value: '0'

- name: "Enaable sshd? {{ sshd_enable }}"
  community.general.sysrc:
    name: sshd_enable
    value: "{{ sshd_enable }}"
    state: present

- name: Enable H-TCP
  community.general.sysrc:
    name: cc_htcp_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable ntpd
  community.general.sysrc:
    name: ntpd_enable
    value: "YES"
    state: present

- name: System clock sync on startup
  community.general.sysrc:
    name: ntpd_sync_on_start
    value: "YES"
    state: present

- name: Enable microcode updates
  community.general.sysrc:
    name: microcode_update_enable
    value: "YES"
    state: present

- name: Enable coretemp
  community.general.sysrc:
    name: coretemp_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable AES
  community.general.sysrc:
    name: aesni_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable AHCI
  community.general.sysrc:
    name: ahci_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Enable aio
  community.general.sysrc:
    name: aio_load
    state: present
    value: "YES"
    path: /boot/loader.conf

- name: Clear /tmp
  community.general.sysrc:
    name: clear_tmp_enable
    value: "YES"
    state: present

- name: Change loader logo
  community.general.sysrc:
    name: loader_logo
    state: present
    value: "beastie"
    path: /boot/loader.conf

- name: Enable sshd
  community.general.sysrc:
    name: sshd_enable
    value: "YES"
    state: present

- name: Set syslogd flags
  community.general.sysrc:
    name: syslogd_flags
    value: "-ss"
    state: present

- name: Enable Kernel security levels
  community.general.sysrc:
    name: kern_securelevel_enable
    value: "YES"
    state: present
  when: set_security_level

- name: Set kernel security level
  community.general.sysrc:
    name: kern_securelevel
    value: "{{ security_level }}"
    state: present
  when: set_security_level

- name: Fix file permissions
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: wheel
    mode: '0600'
  loop:
    - /etc/crontab
    - /etc/ssh/sshd_config
