---

- name: Upgrade installed packages
  community.general.pkgng:
    name: "*"
    state: latest
  become: true
  when: upgrade_packages

- name: Copy MOTD
  ansible.builtin.copy:
    src: motd.sh
    dest: /etc/motd.sh
    owner: root
    mode: 0755
  become: true

- name: Install MOTD
  ansible.builtin.cron:
    name: "Update MOTD"
    special_time: reboot
    job: "/etc/motd.sh > /etc/motd.template"
    user: root
    state: present
  become: true

- name: Configure make
  ansible.builtin.template:
    src: make.conf.j2
    dest: /etc/make.conf
    owner: root
    group: wheel
    mode: 0644
  become: true
