---

- name: Upgrade installed packages
  pkgng:
    name: "*"
    state: latest
  become: True

- name: Enable coretemp
  community.general.sysrc:
    name: coretemp_load
    state: present
    value: "YES"
    path: /boot/loader.conf
  become: True

- name: Enable AES
  community.general.sysrc:
    name: aesni_load
    state: present
    value: "YES"
    path: /boot/loader.conf
  become: True

- name: Enable sshd
  community.general.sysrc:
    name: sshd_enable
    value: "YES"
    state: present
  become: True

- name: Copy MOTD
  copy:
    src: motd.sh
    dest: /etc/motd.sh
    owner: root
    mode: 0755
  become: True

- name: Install MOTD
  cron:
    name: "Update MOTD"
    special_time: reboot
    job: "/etc/motd.sh > /etc/motd.template"
    user: root
    state: present
  become: True

- name: Edit shell prompt
  lineinfile:
    dest: /home/{{ ansible_user_id }}/.shrc
    line: 'export PS1="\u@\H x: "'
    owner: "{{ ansible_user_id }}"
    state: present

- name: Install ohmyzsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh"
  register: ohmyzsh
