---

- name: Upgrade installed packages
  community.general.pkgng:
    name: "*"
    state: latest
  become: True

- name: Hide UIDs
  ansible.posix.sysctl:
    name: security.bsd.see_other_uids
    state: present
    value: '0'
  become: True

- name: Random IP packet IDs
  ansible.posix.sysctl:
    name: net.inet.ip.random_id
    state: present
    value: '1'
  become: True

- name: Blackhole 1/2
  ansible.posix.sysctl:
    name: net.inet.tcp.blackhole
    state: present
    value: '2'
  become: True

- name: Blackhole 2/2
  ansible.posix.sysctl:
    name: net.inet.udp.blackhole
    state: present
    value: '1'
  become: True

- name: Enable microcode updates
  community.general.sysrc:
    name: microcode_update_enable
    value: "YES"
    state: present
  become: True

- name: Enable coretemp
  community.general.sysrc:
    name: coretemp_load
    state: present
    value: "YES"
    path: /boot/loader.conf
  become: True

- name: Enable AES
  community.general.sysrc:
    name: aesni_load
    state: present
    value: "YES"
    path: /boot/loader.conf
  become: True

- name: Enable AHCI
  community.general.sysrc:
    name: ahci_load
    state: present
    value: "YES"
    path: /boot/loader.conf
  become: True

- name: Enable aio
  community.general.sysrc:
    name: aio_load
    state: present
    value: "YES"
    path: /boot/loader.conf
  become: True

- name: Clear /tmp
  community.general.sysrc:
    name: clear_tmp_enable
    value: "YES"
    state: present
  become: True

- name: Enable H-TCP
  community.general.sysrc:
    name: cc_htcp_load
    state: present
    value: "YES"
    path: /boot/loader.conf
  become: True

- name: Change loader logo
  community.general.sysrc:
    name: loader_logo
    state: present
    value: "beastie"
    path: /boot/loader.conf
  become: True

- name: Disable sendmail
  community.general.sysrc:
    name: sendmail_enable
    value: "NONE"
    state: present
  become: True

- name: Enable sshd
  community.general.sysrc:
    name: sshd_enable
    value: "YES"
    state: present
  become: True

- name: Enable Kernel security levels
  community.general.sysrc:
    name: kern_securelevel_enable
    value: "YES"
    state: present
  become: True

- name: Set kernel security level
  community.general.sysrc:
    name: kern_securelevel
    value: "2"
    state: present
  become: True

- name: Set syslogd flags
  community.general.sysrc:
    name: syslogd_flags
    value: "-ss"
    state: present
  become: True

- name: Copy MOTD
  copy:
    src: motd.sh
    dest: /etc/motd.sh
    owner: root
    mode: 0755
  become: True

- name: Install MOTD
  cron:
    name: "Update MOTD"
    special_time: reboot
    job: "/etc/motd.sh > /etc/motd.template"
    user: root
    state: present
  become: True

- name: Edit shell prompt
  lineinfile:
    dest: /home/{{ ansible_user_id }}/.shrc
    line: 'export PS1="\u@\H x: "'
    owner: "{{ ansible_user_id }}"
    state: present

- name: Install ohmyzsh
  shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh"
  register: ohmyzsh
