---

- name: Upgrade installed packages
  community.general.pkgng:
    name: "*"
    state: latest
  become: true

- name: Copy MOTD
  ansible.builtin.copy:
    src: motd.sh
    dest: /etc/motd.sh
    owner: root
    mode: 0755
  become: true

- name: Install MOTD
  ansible.builtin.cron:
    name: "Update MOTD"
    special_time: reboot
    job: "/etc/motd.sh > /etc/motd.template"
    user: root
    state: present
  become: true

- name: Edit shell prompt
  ansible.builtin.lineinfile:
    dest: /home/{{ ansible_user_id }}/.shrc
    line: 'export PS1="\u@\H x: "'
    owner: "{{ ansible_user_id }}"
    state: present

- name: Install ohmyzsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "/home/{{ ansible_user_id }}/.oh-my-zsh"
  register: ohmyzsh
